In [2]:
import pandas as pd
import datetime
import numpy as np

_Data Cleaning and Pre-processing_

In [3]:
# Import csv files into dataframes
price_demand_file = 'price_demand_data.csv'
weather_file = 'weather_data.csv'
price_demand = pd.read_csv(price_demand_file)
weather = pd.read_csv(weather_file)
                          
# Replace empty cells with NaN
empty_values = ['', ' ', '   ']
price_demand = price_demand.replace(empty_values, np.nan)
weather = weather.replace(empty_values, np.nan)

### Before Data Cleaning Summary
__price demand data__
1. Missing data: Yes 
   <font size="2">(Expecting 11665 rows but only has 11664 rows)</font>

2. Duplicates: No

In [4]:
# Before data cleaning
display(price_demand.shape)
display(price_demand.info())
display(price_demand.isnull().sum())

for col in price_demand.columns:
    print(col, price_demand[col].unique())

(11664, 4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11664 entries, 0 to 11663
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   REGION          11664 non-null  object
 1   SETTLEMENTDATE  11664 non-null  object
 2   TOTALDEMAND     11664 non-null  float64
 3   PRICECATEGORY   11664 non-null  object
dtypes: float64(1), object(3)
memory usage: 364.6+ KB

None

REGION            0
SETTLEMENTDATE    0
TOTALDEMAND       0
PRICECATEGORY     0
dtype: int64

REGION ['VIC1']
SETTLEMENTDATE ['1/01/2021 0:30' '1/01/2021 1:00' '1/01/2021 1:30' ... '31/08/2021 23:00'
 '31/08/2021 23:30' '1/09/2021 0:00']
TOTALDEMAND [4179.21 4047.76 3934.7  ... 4620.09 4834.   4811.27]
PRICECATEGORY ['LOW' 'MEDIUM' 'HIGH' 'EXTREME']

In [5]:
# Convert each column into suitable datatype
price_demand['REGION'] = price_demand['REGION'].astype('string')
price_demand['PRICECATEGORY'] = price_demand['PRICECATEGORY'].astype('string')


price_demand['SETTLEMENTDATE'] = pd.to_datetime(price_demand['SETTLEMENTDATE'], format='%d/%m/%Y %H:%M')

# Split 'SETTLEMENTDATE' into 'DATE' and 'TIME'
price_demand['DATE'] = price_demand['SETTLEMENTDATE'].dt.date
price_demand['DATE'] = pd.to_datetime(price_demand['DATE'], format='%Y/%m/%d')
price_demand['TIME'] = price_demand['SETTLEMENTDATE'].dt.time
price_demand['MONTH'] = price_demand['DATE'].dt.month
price_demand['MONTH'] = price_demand['MONTH'].astype(int)

price_demand['REGION'] = price_demand['REGION'].astype('string')
price_demand['PRICECATEGORY'] = price_demand['PRICECATEGORY'].astype('string')

In [6]:
# Checking missing data for dates
# Get the start date/end date of dataset
price_start_date = price_demand['SETTLEMENTDATE'].min().date()
price_end_date = price_demand['SETTLEMENTDATE'].max().date()

delta = price_end_date - price_start_date 

# Total number of days appeared in the datasets
num_days = delta.days + 1
expected_entry = num_days * 48 # 48 entries per day
print(f"Total number of days: {num_days}")
print(f"Expected row numbers: {expected_entry}")
settlementdate_dup = price_demand['SETTLEMENTDATE'].duplicated().sum()
print(f"Missing row count: {expected_entry - price_demand.shape[0]}")
print(f"Duplicated Settlementdate data: {settlementdate_dup}")

Total number of days: 244
Expected row numbers: 11712
Missing row count: 48
Duplicated Settlementdate data: 0

In [7]:
#After data cleaning
display(price_demand.shape)
display(price_demand.info())
display(price_demand.isnull().sum())
display(price_demand.head(5))
display(price_demand.tail(5))

(11664, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11664 entries, 0 to 11663
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   REGION          11664 non-null  string
 1   SETTLEMENTDATE  11664 non-null  datetime64[ns]
 2   TOTALDEMAND     11664 non-null  float64
 3   PRICECATEGORY   11664 non-null  string
 4   DATE            11664 non-null  datetime64[ns]
 5   TIME            11664 non-null  object
 6   MONTH           11664 non-null  int32
dtypes: datetime64[ns](2), float64(1), int32(1), object(1), string(2)
memory usage: 592.4+ KB

None

REGION            0
SETTLEMENTDATE    0
TOTALDEMAND       0
PRICECATEGORY     0
DATE              0
TIME              0
MONTH             0
dtype: int64

,REGION,SETTLEMENTDATE,TOTALDEMAND,PRICECATEGORY,DATE,TIME,MONTH
0,VIC1,2021-01-01 00:30:00,4179.21,LOW,2021-01-01,00:30:00,1
1,VIC1,2021-01-01 01:00:00,4047.76,LOW,2021-01-01,01:00:00,1
2,VIC1,2021-01-01 01:30:00,3934.70,LOW,2021-01-01,01:30:00,1
3,VIC1,2021-01-01 02:00:00,3766.45,LOW,2021-01-01,02:00:00,1
4,VIC1,2021-01-01 02:30:00,3590.37,LOW,2021-01-01,02:30:00,1

,REGION,SETTLEMENTDATE,TOTALDEMAND,PRICECATEGORY,DATE,TIME,MONTH
11659,VIC1,2021-08-31 22:00:00,4861.91,MEDIUM,2021-08-31,22:00:00,8
11660,VIC1,2021-08-31 22:30:00,4748.74,MEDIUM,2021-08-31,22:30:00,8
11661,VIC1,2021-08-31 23:00:00,4620.09,MEDIUM,2021-08-31,23:00:00,8
11662,VIC1,2021-08-31 23:30:00,4834.00,MEDIUM,2021-08-31,23:30:00,8
11663,VIC1,2021-09-01 00:00:00,4811.27,MEDIUM,2021-09-01,00:00:00,9

In [8]:
# Before data cleaning
display(weather.shape)
display(weather.info())
display(weather.isnull().sum())
display(weather.head(5))
display(weather.tail(5))

(243, 21)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               243 non-null    object
 1   Minimum temperature (°C)           242 non-null    float64
 2   Maximum temperature (°C)           242 non-null    float64
 3   Rainfall (mm)                      241 non-null    float64
 4   Evaporation (mm)                   243 non-null    float64
 5   Sunshine (hours)                   243 non-null    float64
 6   Direction of maximum wind gust     240 non-null    object
 7   Speed of maximum wind gust (km/h)  240 non-null    float64
 8   Time of maximum wind gust          240 non-null    object
 9   9am Temperature (°C)               242 non-null    float64
 10  9am relative humidity (%)          242 non-null    float64
 11  9am cloud amount (oktas)           243 non-null    int64
 12  9am wind direction                 228 non-null    object
 13  9am wind speed (km/h)              242 non-null    object
 14  9am MSL pressure (hPa)             241 non-null    float64
 15  3pm Temperature (°C)               243 non-null    float64
 16  3pm relative humidity (%)          243 non-null    int64
 17  3pm cloud amount (oktas)           242 non-null    float64
 18  3pm wind direction                 238 non-null    object
 19  3pm wind speed (km/h)              243 non-null    object
 20  3pm MSL pressure (hPa)             242 non-null    float64
dtypes: float64(12), int64(2), object(7)
memory usage: 40.0+ KB

None

Date                                  0
Minimum temperature (°C)              1
Maximum temperature (°C)              1
Rainfall (mm)                         2
Evaporation (mm)                      0
Sunshine (hours)                      0
Direction of maximum wind gust        3
Speed of maximum wind gust (km/h)     3
Time of maximum wind gust             3
9am Temperature (°C)                  1
9am relative humidity (%)             1
9am cloud amount (oktas)              0
9am wind direction                   15
9am wind speed (km/h)                 1
9am MSL pressure (hPa)                2
3pm Temperature (°C)                  0
3pm relative humidity (%)             0
3pm cloud amount (oktas)              1
3pm wind direction                    5
3pm wind speed (km/h)                 0
3pm MSL pressure (hPa)                1
dtype: int64

,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,9am Temperature (°C),...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
0,1/01/2021,15.6,29.9,0.0,2.8,9.3,NNE,31.0,13:14,19.2,...,6,N,2,1018.8,28.1,43,5.0,E,13,1015.3
1,2/01/2021,18.4,29.0,0.0,9.4,1.3,NNW,30.0,8:22,23.3,...,7,NNW,17,1013.3,28.7,38,7.0,SW,4,1008.5
2,3/01/2021,17.0,26.2,12.6,4.8,7.1,WSW,33.0,17:55,18.3,...,8,WSW,4,1007.7,23.5,59,4.0,SSW,2,1005.2
3,4/01/2021,16.0,18.6,2.6,3.8,0.0,SSE,41.0,16:03,16.2,...,8,SSE,11,1010.0,18.2,82,8.0,SSW,17,1011.0
4,5/01/2021,15.9,19.1,11.2,1.0,0.0,SSE,35.0,11:02,17.2,...,8,SSE,13,1012.5,18.2,82,8.0,SSE,19,1013.3

,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,9am Temperature (°C),...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
238,27/08/2021,4.6,13.6,0.0,1.2,3.8,SSW,15.0,12:18,7.7,...,7,NaN,Calm,1020.0,12.8,65,7.0,SSE,7,1017.4
239,28/08/2021,5.3,17.8,0.0,1.6,9.6,N,39.0,13:14,9.1,...,1,N,7,1018.6,17.4,31,3.0,NNW,24,1013.5
240,29/08/2021,9.1,16.2,0.6,6.4,4.3,NNE,33.0,1:50,10.6,...,7,N,13,1011.4,12.8,84,7.0,S,6,1010.4
241,30/08/2021,6.4,17.6,4.0,1.4,7.4,NNW,50.0,14:04,11.1,...,7,N,15,1016.1,16.8,45,1.0,NNW,28,1013.2
242,31/08/2021,11.0,20.1,0.0,5.8,3.6,N,61.0,16:29,13.5,...,7,N,17,NaN,19.4,43,6.0,N,30,1012.2

In [9]:
# Date column pre-processing
weather['Date'] = pd.to_datetime(weather['Date'], format='%d/%m/%Y')

# Add Month column for data analysis purpose
weather['Month'] = weather['Date'].dt.month
weather['Month'] = weather['Month'].astype(int)

# Checking missing rows based on date
# start_date
display(weather['Date'].min())
# end_date
display(weather['Date'].max())

# number of days
weather_start_date = weather['Date'].min().date()
weather_end_date = weather['Date'].max().date()

delta = weather_end_date - weather_start_date
weather_num_days = delta.days + 1
print(f"Total number of days: {weather_num_days}")
print(f"Expected row numbers: {weather_num_days}")
weather_date_dup = weather['Date'].duplicated().sum()
print(f"Missing row count: {weather_num_days - weather.shape[0]}")
print(f"Duplicated Weather data: {weather_date_dup}")

Timestamp('2021-01-01 00:00:00')

Timestamp('2021-08-31 00:00:00')

Total number of days: 243
Expected row numbers: 243
Missing row count: 0
Duplicated Weather data: 0

In [10]:
# Replace 'Calm' with 0 in '9am/3pm wind speed (km/h)' columns
weather['9am wind speed (km/h)'] = weather['9am wind speed (km/h)'].apply(lambda x: x if x != 'Calm' else 0)
weather['3pm wind speed (km/h)'] = weather['3pm wind speed (km/h)'].apply(lambda x: x if x != 'Calm' else 0)

# For continuous data - use interpolate to impute missing data
interpolate_missing_data = ['Rainfall (mm)','Speed of maximum wind gust (km/h)', '9am relative humidity (%)', '9am wind speed (km/h)','3pm cloud amount (oktas)', 'Minimum temperature (°C)', 'Maximum temperature (°C)', '9am Temperature (°C)', '9am MSL pressure (hPa)', '3pm MSL pressure (hPa)']

weather[interpolate_missing_data] = weather[interpolate_missing_data].interpolate(method='linear', limit=2)

In [11]:
# For Categorical data - find out mode values based on Month
grouped_by_month = weather.groupby(weather['Month'])

direction_max_wind_mode = grouped_by_month['Direction of maximum wind gust '].agg(pd.Series.mode)
time_max_wind_mode = grouped_by_month['Time of maximum wind gust'].agg(pd.Series.mode)
direction_9am_mode = grouped_by_month['9am wind direction'].agg(pd.Series.mode)
direction_3pm_mode = grouped_by_month['3pm wind direction'].agg(pd.Series.mode)
wind_sp_9am = grouped_by_month['9am wind speed (km/h)'].agg(pd.Series.mode)

display(direction_max_wind_mode)
display(time_max_wind_mode)
display(direction_9am_mode)
display(direction_3pm_mode)
display(wind_sp_9am)

Month
1         SSW
2         SSW
3         SSW
4         SSW
5           N
6           N
7    [N, NNW]
8           N
Name: Direction of maximum wind gust , dtype: object

Month
1    [11:02, 11:59, 12:19, 13:00, 13:14, 13:20, 13:...
2    [10:27, 11:22, 11:23, 11:44, 12:20, 12:58, 13:...
3                                                14:21
4    [10:50, 10:53, 11:20, 11:45, 11:49, 12:02, 12:...
5                                       [12:48, 14:15]
6    [0:05, 0:33, 0:39, 10:33, 10:38, 10:40, 10:49,...
7    [0:37, 10:29, 10:33, 10:41, 11:20, 12:08, 12:1...
8    [0:12, 10:24, 11:11, 11:13, 11:24, 12:08, 12:0...
Name: Time of maximum wind gust, dtype: object

Month
1                   SSE
2            [NNE, SSE]
3                    NE
4    [N, NNE, NNW, WNW]
5                   NNE
6                     N
7                     N
8                     N
Name: 9am wind direction, dtype: object

Month
1    SSW
2    SSW
3    SSW
4    SSW
5    SSW
6      N
7      N
8      W
Name: 3pm wind direction, dtype: object

Month
1         13
2          7
3          9
4          9
5    [11, 9]
6          7
7         13
8         11
Name: 9am wind speed (km/h), dtype: object

In [12]:
# Function to get the 1st mode value if there are multiple ones
def get_mode(mode_by_month, month):
    """
    Get the most common value by month.
    In case there are more than 1 most common value, return the 1st one from the list.
    """
    if isinstance(mode_by_month[month], str): 
        return mode_by_month[month]
    return mode_by_month[month][0]

# Function to replace NaN with mode values
def fillna_with_mode(row):
    """
    Replace NaN with the most common value returned from get_mode() function.
    """
    if pd.isna(row['Direction of maximum wind gust ']):
        row['Direction of maximum wind gust '] = get_mode(direction_max_wind_mode, row['Month'])
    if pd.isna(row['Time of maximum wind gust']):
        row['Time of maximum wind gust'] = get_mode(time_max_wind_mode, row['Month'])
    if pd.isna(row['9am wind direction']):
        row['9am wind direction'] = get_mode(direction_9am_mode, row['Month'])
    if pd.isna(row['3pm wind direction']):
        row['3pm wind direction'] = get_mode(direction_3pm_mode, row['Month'])
    if pd.isna(row['9am wind speed (km/h)']):
        row['9am wind speed (km/h)'] = get_mode(wind_sp_9am, row['Month'])
    return row

In [13]:
# Replace NaN value with the most common value.
weather = weather.apply(fillna_with_mode, axis=1)

In [14]:
# Convert TIME into datetime.time type.
def convert_time(x):
    time_split = x.split(':')
    hour = int(time_split[0])
    mins = int(time_split[1])
    return datetime.time(hour, mins)

weather['Time of maximum wind gust'] = weather['Time of maximum wind gust'].astype('str')
weather['Time of maximum wind gust'] = weather['Time of maximum wind gust'].apply(lambda x: convert_time(x))

In [15]:
# Split features into float, int and string type for transforming
float_type_data = ['Minimum temperature (°C)', 'Maximum temperature (°C)', 
                   'Rainfall (mm)', 'Evaporation (mm)', 'Sunshine (hours)','9am Temperature (°C)','9am MSL pressure (hPa)', '3pm Temperature (°C)', '3pm MSL pressure (hPa)']

string_type_Data = ['Direction of maximum wind gust ', '9am wind direction', '3pm wind direction']

int_type_data = ['Speed of maximum wind gust (km/h)', '9am relative humidity (%)', '9am cloud amount (oktas)','9am wind speed (km/h)', '3pm relative humidity (%)', '3pm cloud amount (oktas)', '3pm wind speed (km/h)']

# Convert the dtype of the columns into suitable ones
weather[float_type_data] = weather[float_type_data].round(1).astype(float)
weather[string_type_Data] = weather[string_type_Data].astype('string')
weather[int_type_data] = weather[int_type_data].round().astype(int)

In [16]:
# After data cleaning
display(weather.shape)
display(weather.info())
display(weather.isnull().sum())
display(weather.head(5))
display(weather.tail(5))

(243, 22)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Date                               243 non-null    datetime64[ns]
 1   Minimum temperature (°C)           243 non-null    float64
 2   Maximum temperature (°C)           243 non-null    float64
 3   Rainfall (mm)                      243 non-null    float64
 4   Evaporation (mm)                   243 non-null    float64
 5   Sunshine (hours)                   243 non-null    float64
 6   Direction of maximum wind gust     243 non-null    string
 7   Speed of maximum wind gust (km/h)  243 non-null    int32
 8   Time of maximum wind gust          243 non-null    object
 9   9am Temperature (°C)               243 non-null    float64
 10  9am relative humidity (%)          243 non-null    int32
 11  9am cloud amount (oktas)           243 non-null    int32
 12  9am wind direction                 243 non-null    string
 13  9am wind speed (km/h)              243 non-null    int32
 14  9am MSL pressure (hPa)             243 non-null    float64
 15  3pm Temperature (°C)               243 non-null    float64
 16  3pm relative humidity (%)          243 non-null    int32
 17  3pm cloud amount (oktas)           243 non-null    int32
 18  3pm wind direction                 243 non-null    string
 19  3pm wind speed (km/h)              243 non-null    int32
 20  3pm MSL pressure (hPa)             243 non-null    float64
 21  Month                              243 non-null    int64
dtypes: datetime64[ns](1), float64(9), int32(7), int64(1), object(1), string(3)
memory usage: 35.2+ KB

None

Date                                 0
Minimum temperature (°C)             0
Maximum temperature (°C)             0
Rainfall (mm)                        0
Evaporation (mm)                     0
Sunshine (hours)                     0
Direction of maximum wind gust       0
Speed of maximum wind gust (km/h)    0
Time of maximum wind gust            0
9am Temperature (°C)                 0
9am relative humidity (%)            0
9am cloud amount (oktas)             0
9am wind direction                   0
9am wind speed (km/h)                0
9am MSL pressure (hPa)               0
3pm Temperature (°C)                 0
3pm relative humidity (%)            0
3pm cloud amount (oktas)             0
3pm wind direction                   0
3pm wind speed (km/h)                0
3pm MSL pressure (hPa)               0
Month                                0
dtype: int64

,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,9am Temperature (°C),...,9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa),Month
0,2021-01-01,15.6,29.9,0.0,2.8,9.3,NNE,31,13:14:00,19.2,...,N,2,1018.8,28.1,43,5,E,13,1015.3,1
1,2021-01-02,18.4,29.0,0.0,9.4,1.3,NNW,30,08:22:00,23.3,...,NNW,17,1013.3,28.7,38,7,SW,4,1008.5,1
2,2021-01-03,17.0,26.2,12.6,4.8,7.1,WSW,33,17:55:00,18.3,...,WSW,4,1007.7,23.5,59,4,SSW,2,1005.2,1
3,2021-01-04,16.0,18.6,2.6,3.8,0.0,SSE,41,16:03:00,16.2,...,SSE,11,1010.0,18.2,82,8,SSW,17,1011.0,1
4,2021-01-05,15.9,19.1,11.2,1.0,0.0,SSE,35,11:02:00,17.2,...,SSE,13,1012.5,18.2,82,8,SSE,19,1013.3,1

,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,9am Temperature (°C),...,9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa),Month
238,2021-08-27,4.6,13.6,0.0,1.2,3.8,SSW,15,12:18:00,7.7,...,N,0,1020.0,12.8,65,7,SSE,7,1017.4,8
239,2021-08-28,5.3,17.8,0.0,1.6,9.6,N,39,13:14:00,9.1,...,N,7,1018.6,17.4,31,3,NNW,24,1013.5,8
240,2021-08-29,9.1,16.2,0.6,6.4,4.3,NNE,33,01:50:00,10.6,...,N,13,1011.4,12.8,84,7,S,6,1010.4,8
241,2021-08-30,6.4,17.6,4.0,1.4,7.4,NNW,50,14:04:00,11.1,...,N,15,1016.1,16.8,45,1,NNW,28,1013.2,8
242,2021-08-31,11.0,20.1,0.0,5.8,3.6,N,61,16:29:00,13.5,...,N,17,1016.1,19.4,43,6,N,30,1012.2,8

Export Pickle (serialize) object to file

In [17]:
weather.to_pickle("./new_weather.pkl")  
price_demand.to_pickle("./new_price_demand.pkl")

Export data to CSVs

In [18]:
weather.to_csv('new_weather.csv', index = False)
price_demand.to_csv('new_price_demand.csv', index = False)